import "./globals.css";
import Nav from "../components/Nav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex justify-center">
          <div className="max-w-screen-2xl w-full px-4 sm:px-6 lg:px-8">
            <Nav />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
